namespace BOOKIFY
{
    partial class returnPenalty
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(returnPenalty));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblPenaltyHeader = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPenaltyBTitle = new System.Windows.Forms.Label();
            this.lblPenaltyDDate = new System.Windows.Forms.Label();
            this.lblPenaltyDReturned = new System.Windows.Forms.Label();
            this.lblPenaltyPnlty = new System.Windows.Forms.Label();
            this.lblPenaltyTotal = new System.Windows.Forms.Label();
            this.lblPenaltyPayment = new System.Windows.Forms.Label();
            this.lblPenaltyChange = new System.Windows.Forms.Label();
            this.penaltyCalculateBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.penaltyReturnBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.penaltyDReturned = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.penaltyPayment = new Bunifu.UI.WinForms.BunifuTextBox();
            this.penaltyTotal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.penaltyChange = new Bunifu.UI.WinForms.BunifuTextBox();
            this.penaltyBTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.penaltyDDate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.penaltyPnlty = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.lblPenaltyHeader);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1196, 110);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // lblPenaltyHeader
            // 
            this.lblPenaltyHeader.AllowParentOverrides = false;
            this.lblPenaltyHeader.AutoEllipsis = false;
            this.lblPenaltyHeader.AutoSize = false;
            this.lblPenaltyHeader.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPenaltyHeader.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPenaltyHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPenaltyHeader.Font = new System.Drawing.Font("Montserrat Black", 22F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyHeader.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyHeader.Location = new System.Drawing.Point(0, 0);
            this.lblPenaltyHeader.Name = "lblPenaltyHeader";
            this.lblPenaltyHeader.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPenaltyHeader.Size = new System.Drawing.Size(1196, 110);
            this.lblPenaltyHeader.TabIndex = 0;
            this.lblPenaltyHeader.Text = "Return Book";
            this.lblPenaltyHeader.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPenaltyHeader.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPenaltyBTitle
            // 
            this.lblPenaltyBTitle.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyBTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyBTitle.Location = new System.Drawing.Point(22, 125);
            this.lblPenaltyBTitle.Name = "lblPenaltyBTitle";
            this.lblPenaltyBTitle.Size = new System.Drawing.Size(202, 41);
            this.lblPenaltyBTitle.TabIndex = 3;
            this.lblPenaltyBTitle.Text = "Book Title:";
            this.lblPenaltyBTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblPenaltyDDate
            // 
            this.lblPenaltyDDate.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyDDate.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyDDate.Location = new System.Drawing.Point(22, 200);
            this.lblPenaltyDDate.Name = "lblPenaltyDDate";
            this.lblPenaltyDDate.Size = new System.Drawing.Size(202, 42);
            this.lblPenaltyDDate.TabIndex = 4;
            this.lblPenaltyDDate.Text = "Due Date:";
            this.lblPenaltyDDate.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblPenaltyDReturned
            // 
            this.lblPenaltyDReturned.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyDReturned.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyDReturned.Location = new System.Drawing.Point(22, 281);
            this.lblPenaltyDReturned.Name = "lblPenaltyDReturned";
            this.lblPenaltyDReturned.Size = new System.Drawing.Size(240, 42);
            this.lblPenaltyDReturned.TabIndex = 5;
            this.lblPenaltyDReturned.Text = "Date Returned:";
            this.lblPenaltyDReturned.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblPenaltyPnlty
            // 
            this.lblPenaltyPnlty.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyPnlty.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyPnlty.Location = new System.Drawing.Point(22, 370);
            this.lblPenaltyPnlty.Name = "lblPenaltyPnlty";
            this.lblPenaltyPnlty.Size = new System.Drawing.Size(240, 42);
            this.lblPenaltyPnlty.TabIndex = 6;
            this.lblPenaltyPnlty.Text = "Penalty:";
            this.lblPenaltyPnlty.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblPenaltyTotal
            // 
            this.lblPenaltyTotal.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyTotal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyTotal.Location = new System.Drawing.Point(695, 211);
            this.lblPenaltyTotal.Name = "lblPenaltyTotal";
            this.lblPenaltyTotal.Size = new System.Drawing.Size(240, 42);
            this.lblPenaltyTotal.TabIndex = 7;
            this.lblPenaltyTotal.Text = "Total:";
            this.lblPenaltyTotal.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPenaltyTotal.Click += new System.EventHandler(this.label5_Click);
            // 
            // lblPenaltyPayment
            // 
            this.lblPenaltyPayment.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyPayment.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyPayment.Location = new System.Drawing.Point(695, 131);
            this.lblPenaltyPayment.Name = "lblPenaltyPayment";
            this.lblPenaltyPayment.Size = new System.Drawing.Size(240, 42);
            this.lblPenaltyPayment.TabIndex = 8;
            this.lblPenaltyPayment.Text = "Payment:";
            this.lblPenaltyPayment.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblPenaltyChange
            // 
            this.lblPenaltyChange.Font = new System.Drawing.Font("Montserrat", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPenaltyChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(73)))), ((int)(((byte)(72)))));
            this.lblPenaltyChange.Location = new System.Drawing.Point(695, 297);
            this.lblPenaltyChange.Name = "lblPenaltyChange";
            this.lblPenaltyChange.Size = new System.Drawing.Size(240, 42);
            this.lblPenaltyChange.TabIndex = 9;
            this.lblPenaltyChange.Text = "Change:";
            this.lblPenaltyChange.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // penaltyCalculateBtn
            // 
            this.penaltyCalculateBtn.AllowAnimations = true;
            this.penaltyCalculateBtn.AllowMouseEffects = true;
            this.penaltyCalculateBtn.AllowToggling = false;
            this.penaltyCalculateBtn.AnimationSpeed = 200;
            this.penaltyCalculateBtn.AutoGenerateColors = false;
            this.penaltyCalculateBtn.AutoRoundBorders = false;
            this.penaltyCalculateBtn.AutoSizeLeftIcon = true;
            this.penaltyCalculateBtn.AutoSizeRightIcon = true;
            this.penaltyCalculateBtn.BackColor = System.Drawing.Color.Transparent;
            this.penaltyCalculateBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyCalculateBtn.BackgroundImage")));
            this.penaltyCalculateBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyCalculateBtn.ButtonText = "Calculate";
            this.penaltyCalculateBtn.ButtonTextMarginLeft = 0;
            this.penaltyCalculateBtn.ColorContrastOnClick = 45;
            this.penaltyCalculateBtn.ColorContrastOnHover = 45;
            this.penaltyCalculateBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.penaltyCalculateBtn.CustomizableEdges = borderEdges1;
            this.penaltyCalculateBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.penaltyCalculateBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.penaltyCalculateBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyCalculateBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.penaltyCalculateBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.penaltyCalculateBtn.Font = new System.Drawing.Font("Montserrat", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.penaltyCalculateBtn.ForeColor = System.Drawing.Color.White;
            this.penaltyCalculateBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.penaltyCalculateBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.penaltyCalculateBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.penaltyCalculateBtn.IconMarginLeft = 11;
            this.penaltyCalculateBtn.IconPadding = 10;
            this.penaltyCalculateBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.penaltyCalculateBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.penaltyCalculateBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.penaltyCalculateBtn.IconSize = 25;
            this.penaltyCalculateBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.IdleBorderRadius = 20;
            this.penaltyCalculateBtn.IdleBorderThickness = 1;
            this.penaltyCalculateBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.IdleIconLeftImage = null;
            this.penaltyCalculateBtn.IdleIconRightImage = null;
            this.penaltyCalculateBtn.IndicateFocus = false;
            this.penaltyCalculateBtn.Location = new System.Drawing.Point(375, 487);
            this.penaltyCalculateBtn.Name = "penaltyCalculateBtn";
            this.penaltyCalculateBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.penaltyCalculateBtn.OnDisabledState.BorderRadius = 20;
            this.penaltyCalculateBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyCalculateBtn.OnDisabledState.BorderThickness = 1;
            this.penaltyCalculateBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyCalculateBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.penaltyCalculateBtn.OnDisabledState.IconLeftImage = null;
            this.penaltyCalculateBtn.OnDisabledState.IconRightImage = null;
            this.penaltyCalculateBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyCalculateBtn.onHoverState.BorderRadius = 20;
            this.penaltyCalculateBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyCalculateBtn.onHoverState.BorderThickness = 1;
            this.penaltyCalculateBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyCalculateBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.penaltyCalculateBtn.onHoverState.IconLeftImage = null;
            this.penaltyCalculateBtn.onHoverState.IconRightImage = null;
            this.penaltyCalculateBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.OnIdleState.BorderRadius = 20;
            this.penaltyCalculateBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyCalculateBtn.OnIdleState.BorderThickness = 1;
            this.penaltyCalculateBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.penaltyCalculateBtn.OnIdleState.IconLeftImage = null;
            this.penaltyCalculateBtn.OnIdleState.IconRightImage = null;
            this.penaltyCalculateBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.OnPressedState.BorderRadius = 20;
            this.penaltyCalculateBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyCalculateBtn.OnPressedState.BorderThickness = 1;
            this.penaltyCalculateBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyCalculateBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.penaltyCalculateBtn.OnPressedState.IconLeftImage = null;
            this.penaltyCalculateBtn.OnPressedState.IconRightImage = null;
            this.penaltyCalculateBtn.Size = new System.Drawing.Size(204, 49);
            this.penaltyCalculateBtn.TabIndex = 10;
            this.penaltyCalculateBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.penaltyCalculateBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.penaltyCalculateBtn.TextMarginLeft = 0;
            this.penaltyCalculateBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.penaltyCalculateBtn.UseDefaultRadiusAndThickness = true;
            // 
            // penaltyReturnBtn
            // 
            this.penaltyReturnBtn.AllowAnimations = true;
            this.penaltyReturnBtn.AllowMouseEffects = true;
            this.penaltyReturnBtn.AllowToggling = false;
            this.penaltyReturnBtn.AnimationSpeed = 200;
            this.penaltyReturnBtn.AutoGenerateColors = false;
            this.penaltyReturnBtn.AutoRoundBorders = false;
            this.penaltyReturnBtn.AutoSizeLeftIcon = true;
            this.penaltyReturnBtn.AutoSizeRightIcon = true;
            this.penaltyReturnBtn.BackColor = System.Drawing.Color.Transparent;
            this.penaltyReturnBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyReturnBtn.BackgroundImage")));
            this.penaltyReturnBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyReturnBtn.ButtonText = "Return";
            this.penaltyReturnBtn.ButtonTextMarginLeft = 0;
            this.penaltyReturnBtn.ColorContrastOnClick = 45;
            this.penaltyReturnBtn.ColorContrastOnHover = 45;
            this.penaltyReturnBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.penaltyReturnBtn.CustomizableEdges = borderEdges2;
            this.penaltyReturnBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.penaltyReturnBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.penaltyReturnBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyReturnBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.penaltyReturnBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.penaltyReturnBtn.Font = new System.Drawing.Font("Montserrat", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.penaltyReturnBtn.ForeColor = System.Drawing.Color.White;
            this.penaltyReturnBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.penaltyReturnBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.penaltyReturnBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.penaltyReturnBtn.IconMarginLeft = 11;
            this.penaltyReturnBtn.IconPadding = 10;
            this.penaltyReturnBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.penaltyReturnBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.penaltyReturnBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.penaltyReturnBtn.IconSize = 25;
            this.penaltyReturnBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.IdleBorderRadius = 20;
            this.penaltyReturnBtn.IdleBorderThickness = 1;
            this.penaltyReturnBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.IdleIconLeftImage = null;
            this.penaltyReturnBtn.IdleIconRightImage = null;
            this.penaltyReturnBtn.IndicateFocus = false;
            this.penaltyReturnBtn.Location = new System.Drawing.Point(630, 487);
            this.penaltyReturnBtn.Name = "penaltyReturnBtn";
            this.penaltyReturnBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.penaltyReturnBtn.OnDisabledState.BorderRadius = 20;
            this.penaltyReturnBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyReturnBtn.OnDisabledState.BorderThickness = 1;
            this.penaltyReturnBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyReturnBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.penaltyReturnBtn.OnDisabledState.IconLeftImage = null;
            this.penaltyReturnBtn.OnDisabledState.IconRightImage = null;
            this.penaltyReturnBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyReturnBtn.onHoverState.BorderRadius = 20;
            this.penaltyReturnBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyReturnBtn.onHoverState.BorderThickness = 1;
            this.penaltyReturnBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyReturnBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.penaltyReturnBtn.onHoverState.IconLeftImage = null;
            this.penaltyReturnBtn.onHoverState.IconRightImage = null;
            this.penaltyReturnBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.OnIdleState.BorderRadius = 20;
            this.penaltyReturnBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyReturnBtn.OnIdleState.BorderThickness = 1;
            this.penaltyReturnBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.penaltyReturnBtn.OnIdleState.IconLeftImage = null;
            this.penaltyReturnBtn.OnIdleState.IconRightImage = null;
            this.penaltyReturnBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.penaltyReturnBtn.OnPressedState.BorderRadius = 20;
            this.penaltyReturnBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.penaltyReturnBtn.OnPressedState.BorderThickness = 1;
            this.penaltyReturnBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyReturnBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.penaltyReturnBtn.OnPressedState.IconLeftImage = null;
            this.penaltyReturnBtn.OnPressedState.IconRightImage = null;
            this.penaltyReturnBtn.Size = new System.Drawing.Size(204, 49);
            this.penaltyReturnBtn.TabIndex = 11;
            this.penaltyReturnBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.penaltyReturnBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.penaltyReturnBtn.TextMarginLeft = 0;
            this.penaltyReturnBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.penaltyReturnBtn.UseDefaultRadiusAndThickness = true;
            // 
            // penaltyDReturned
            // 
            this.penaltyDReturned.BackColor = System.Drawing.Color.White;
            this.penaltyDReturned.BorderRadius = 1;
            this.penaltyDReturned.CalendarMonthBackground = System.Drawing.Color.Gray;
            this.penaltyDReturned.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyDReturned.CalendarTitleForeColor = System.Drawing.Color.White;
            this.penaltyDReturned.Color = System.Drawing.Color.White;
            this.penaltyDReturned.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.penaltyDReturned.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Right;
            this.penaltyDReturned.DisabledColor = System.Drawing.Color.Gray;
            this.penaltyDReturned.DisplayWeekNumbers = false;
            this.penaltyDReturned.DPHeight = 0;
            this.penaltyDReturned.FillDatePicker = false;
            this.penaltyDReturned.Font = new System.Drawing.Font("Montserrat", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.penaltyDReturned.ForeColor = System.Drawing.Color.Black;
            this.penaltyDReturned.Icon = ((System.Drawing.Image)(resources.GetObject("penaltyDReturned.Icon")));
            this.penaltyDReturned.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(147)))), ((int)(((byte)(146)))));
            this.penaltyDReturned.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Left;
            this.penaltyDReturned.LeftTextMargin = 5;
            this.penaltyDReturned.Location = new System.Drawing.Point(278, 291);
            this.penaltyDReturned.MinimumSize = new System.Drawing.Size(4, 32);
            this.penaltyDReturned.Name = "penaltyDReturned";
            this.penaltyDReturned.Size = new System.Drawing.Size(385, 32);
            this.penaltyDReturned.TabIndex = 24;
            this.penaltyDReturned.Value = new System.DateTime(2023, 12, 3, 22, 59, 0, 0);
            // 
            // penaltyPayment
            // 
            this.penaltyPayment.AcceptsReturn = false;
            this.penaltyPayment.AcceptsTab = false;
            this.penaltyPayment.AnimationSpeed = 200;
            this.penaltyPayment.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyPayment.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyPayment.BackColor = System.Drawing.Color.Transparent;
            this.penaltyPayment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyPayment.BackgroundImage")));
            this.penaltyPayment.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyPayment.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyPayment.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyPayment.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyPayment.BorderRadius = 15;
            this.penaltyPayment.BorderThickness = 2;
            this.penaltyPayment.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyPayment.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPayment.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.penaltyPayment.DefaultText = "";
            this.penaltyPayment.FillColor = System.Drawing.Color.White;
            this.penaltyPayment.HideSelection = true;
            this.penaltyPayment.IconLeft = null;
            this.penaltyPayment.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPayment.IconPadding = 10;
            this.penaltyPayment.IconRight = null;
            this.penaltyPayment.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPayment.Lines = new string[0];
            this.penaltyPayment.Location = new System.Drawing.Point(857, 125);
            this.penaltyPayment.MaxLength = 32767;
            this.penaltyPayment.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyPayment.Modified = false;
            this.penaltyPayment.Multiline = false;
            this.penaltyPayment.Name = "penaltyPayment";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPayment.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyPayment.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPayment.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPayment.OnIdleState = stateProperties4;
            this.penaltyPayment.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyPayment.PasswordChar = '\0';
            this.penaltyPayment.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyPayment.PlaceholderText = "20.00";
            this.penaltyPayment.ReadOnly = false;
            this.penaltyPayment.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyPayment.SelectedText = "";
            this.penaltyPayment.SelectionLength = 0;
            this.penaltyPayment.SelectionStart = 0;
            this.penaltyPayment.ShortcutsEnabled = true;
            this.penaltyPayment.Size = new System.Drawing.Size(305, 53);
            this.penaltyPayment.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyPayment.TabIndex = 27;
            this.penaltyPayment.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyPayment.TextMarginBottom = 0;
            this.penaltyPayment.TextMarginLeft = 3;
            this.penaltyPayment.TextMarginTop = 0;
            this.penaltyPayment.TextPlaceholder = "20.00";
            this.penaltyPayment.UseSystemPasswordChar = false;
            this.penaltyPayment.WordWrap = true;
            // 
            // penaltyTotal
            // 
            this.penaltyTotal.AcceptsReturn = false;
            this.penaltyTotal.AcceptsTab = false;
            this.penaltyTotal.AnimationSpeed = 200;
            this.penaltyTotal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyTotal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyTotal.BackColor = System.Drawing.Color.Transparent;
            this.penaltyTotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyTotal.BackgroundImage")));
            this.penaltyTotal.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyTotal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyTotal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyTotal.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyTotal.BorderRadius = 15;
            this.penaltyTotal.BorderThickness = 2;
            this.penaltyTotal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyTotal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyTotal.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold);
            this.penaltyTotal.DefaultText = "";
            this.penaltyTotal.FillColor = System.Drawing.Color.White;
            this.penaltyTotal.HideSelection = true;
            this.penaltyTotal.IconLeft = null;
            this.penaltyTotal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyTotal.IconPadding = 10;
            this.penaltyTotal.IconRight = null;
            this.penaltyTotal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyTotal.Lines = new string[0];
            this.penaltyTotal.Location = new System.Drawing.Point(857, 207);
            this.penaltyTotal.MaxLength = 32767;
            this.penaltyTotal.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyTotal.Modified = false;
            this.penaltyTotal.Multiline = false;
            this.penaltyTotal.Name = "penaltyTotal";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyTotal.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyTotal.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyTotal.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyTotal.OnIdleState = stateProperties8;
            this.penaltyTotal.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyTotal.PasswordChar = '\0';
            this.penaltyTotal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.penaltyTotal.PlaceholderText = "";
            this.penaltyTotal.ReadOnly = true;
            this.penaltyTotal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyTotal.SelectedText = "";
            this.penaltyTotal.SelectionLength = 0;
            this.penaltyTotal.SelectionStart = 0;
            this.penaltyTotal.ShortcutsEnabled = true;
            this.penaltyTotal.Size = new System.Drawing.Size(305, 53);
            this.penaltyTotal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyTotal.TabIndex = 28;
            this.penaltyTotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyTotal.TextMarginBottom = 0;
            this.penaltyTotal.TextMarginLeft = 3;
            this.penaltyTotal.TextMarginTop = 0;
            this.penaltyTotal.TextPlaceholder = "";
            this.penaltyTotal.UseSystemPasswordChar = false;
            this.penaltyTotal.WordWrap = true;
            // 
            // penaltyChange
            // 
            this.penaltyChange.AcceptsReturn = false;
            this.penaltyChange.AcceptsTab = false;
            this.penaltyChange.AnimationSpeed = 200;
            this.penaltyChange.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyChange.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyChange.BackColor = System.Drawing.Color.Transparent;
            this.penaltyChange.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyChange.BackgroundImage")));
            this.penaltyChange.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyChange.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyChange.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyChange.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyChange.BorderRadius = 15;
            this.penaltyChange.BorderThickness = 2;
            this.penaltyChange.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyChange.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyChange.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold);
            this.penaltyChange.DefaultText = "";
            this.penaltyChange.FillColor = System.Drawing.Color.White;
            this.penaltyChange.HideSelection = true;
            this.penaltyChange.IconLeft = null;
            this.penaltyChange.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyChange.IconPadding = 10;
            this.penaltyChange.IconRight = null;
            this.penaltyChange.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyChange.Lines = new string[0];
            this.penaltyChange.Location = new System.Drawing.Point(857, 291);
            this.penaltyChange.MaxLength = 32767;
            this.penaltyChange.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyChange.Modified = false;
            this.penaltyChange.Multiline = false;
            this.penaltyChange.Name = "penaltyChange";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyChange.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyChange.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyChange.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyChange.OnIdleState = stateProperties12;
            this.penaltyChange.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyChange.PasswordChar = '\0';
            this.penaltyChange.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.penaltyChange.PlaceholderText = "";
            this.penaltyChange.ReadOnly = true;
            this.penaltyChange.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyChange.SelectedText = "";
            this.penaltyChange.SelectionLength = 0;
            this.penaltyChange.SelectionStart = 0;
            this.penaltyChange.ShortcutsEnabled = true;
            this.penaltyChange.Size = new System.Drawing.Size(305, 53);
            this.penaltyChange.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyChange.TabIndex = 30;
            this.penaltyChange.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyChange.TextMarginBottom = 0;
            this.penaltyChange.TextMarginLeft = 3;
            this.penaltyChange.TextMarginTop = 0;
            this.penaltyChange.TextPlaceholder = "";
            this.penaltyChange.UseSystemPasswordChar = false;
            this.penaltyChange.WordWrap = true;
            // 
            // penaltyBTitle
            // 
            this.penaltyBTitle.AcceptsReturn = false;
            this.penaltyBTitle.AcceptsTab = false;
            this.penaltyBTitle.AnimationSpeed = 200;
            this.penaltyBTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyBTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyBTitle.BackColor = System.Drawing.Color.Transparent;
            this.penaltyBTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyBTitle.BackgroundImage")));
            this.penaltyBTitle.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyBTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyBTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyBTitle.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyBTitle.BorderRadius = 15;
            this.penaltyBTitle.BorderThickness = 2;
            this.penaltyBTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyBTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyBTitle.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold);
            this.penaltyBTitle.DefaultText = "";
            this.penaltyBTitle.FillColor = System.Drawing.Color.White;
            this.penaltyBTitle.HideSelection = true;
            this.penaltyBTitle.IconLeft = null;
            this.penaltyBTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyBTitle.IconPadding = 10;
            this.penaltyBTitle.IconRight = null;
            this.penaltyBTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyBTitle.Lines = new string[0];
            this.penaltyBTitle.Location = new System.Drawing.Point(219, 125);
            this.penaltyBTitle.MaxLength = 32767;
            this.penaltyBTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyBTitle.Modified = false;
            this.penaltyBTitle.Multiline = false;
            this.penaltyBTitle.Name = "penaltyBTitle";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyBTitle.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyBTitle.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyBTitle.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyBTitle.OnIdleState = stateProperties16;
            this.penaltyBTitle.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyBTitle.PasswordChar = '\0';
            this.penaltyBTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.penaltyBTitle.PlaceholderText = "";
            this.penaltyBTitle.ReadOnly = true;
            this.penaltyBTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyBTitle.SelectedText = "";
            this.penaltyBTitle.SelectionLength = 0;
            this.penaltyBTitle.SelectionStart = 0;
            this.penaltyBTitle.ShortcutsEnabled = true;
            this.penaltyBTitle.Size = new System.Drawing.Size(459, 53);
            this.penaltyBTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyBTitle.TabIndex = 31;
            this.penaltyBTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyBTitle.TextMarginBottom = 0;
            this.penaltyBTitle.TextMarginLeft = 3;
            this.penaltyBTitle.TextMarginTop = 0;
            this.penaltyBTitle.TextPlaceholder = "";
            this.penaltyBTitle.UseSystemPasswordChar = false;
            this.penaltyBTitle.WordWrap = true;
            // 
            // penaltyDDate
            // 
            this.penaltyDDate.AcceptsReturn = false;
            this.penaltyDDate.AcceptsTab = false;
            this.penaltyDDate.AnimationSpeed = 200;
            this.penaltyDDate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyDDate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyDDate.BackColor = System.Drawing.Color.Transparent;
            this.penaltyDDate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyDDate.BackgroundImage")));
            this.penaltyDDate.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyDDate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyDDate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyDDate.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyDDate.BorderRadius = 15;
            this.penaltyDDate.BorderThickness = 2;
            this.penaltyDDate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyDDate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyDDate.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold);
            this.penaltyDDate.DefaultText = "";
            this.penaltyDDate.FillColor = System.Drawing.Color.White;
            this.penaltyDDate.HideSelection = true;
            this.penaltyDDate.IconLeft = null;
            this.penaltyDDate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyDDate.IconPadding = 10;
            this.penaltyDDate.IconRight = null;
            this.penaltyDDate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyDDate.Lines = new string[0];
            this.penaltyDDate.Location = new System.Drawing.Point(219, 200);
            this.penaltyDDate.MaxLength = 32767;
            this.penaltyDDate.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyDDate.Modified = false;
            this.penaltyDDate.Multiline = false;
            this.penaltyDDate.Name = "penaltyDDate";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyDDate.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyDDate.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyDDate.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyDDate.OnIdleState = stateProperties20;
            this.penaltyDDate.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyDDate.PasswordChar = '\0';
            this.penaltyDDate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.penaltyDDate.PlaceholderText = "";
            this.penaltyDDate.ReadOnly = true;
            this.penaltyDDate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyDDate.SelectedText = "";
            this.penaltyDDate.SelectionLength = 0;
            this.penaltyDDate.SelectionStart = 0;
            this.penaltyDDate.ShortcutsEnabled = true;
            this.penaltyDDate.Size = new System.Drawing.Size(459, 53);
            this.penaltyDDate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyDDate.TabIndex = 32;
            this.penaltyDDate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyDDate.TextMarginBottom = 0;
            this.penaltyDDate.TextMarginLeft = 3;
            this.penaltyDDate.TextMarginTop = 0;
            this.penaltyDDate.TextPlaceholder = "";
            this.penaltyDDate.UseSystemPasswordChar = false;
            this.penaltyDDate.WordWrap = true;
            // 
            // bunifuTextBox6
            // 
            this.bunifuTextBox6.AcceptsReturn = false;
            this.bunifuTextBox6.AcceptsTab = false;
            this.bunifuTextBox6.AnimationSpeed = 200;
            this.bunifuTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox6.BackgroundImage")));
            this.bunifuTextBox6.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.bunifuTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.bunifuTextBox6.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.bunifuTextBox6.BorderRadius = 15;
            this.bunifuTextBox6.BorderThickness = 2;
            this.bunifuTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox6.DefaultText = "";
            this.bunifuTextBox6.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox6.HideSelection = true;
            this.bunifuTextBox6.IconLeft = null;
            this.bunifuTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.IconPadding = 10;
            this.bunifuTextBox6.IconRight = null;
            this.bunifuTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox6.Lines = new string[0];
            this.bunifuTextBox6.Location = new System.Drawing.Point(268, 281);
            this.bunifuTextBox6.MaxLength = 32767;
            this.bunifuTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox6.Modified = false;
            this.bunifuTextBox6.Multiline = false;
            this.bunifuTextBox6.Name = "bunifuTextBox6";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox6.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox6.OnIdleState = stateProperties24;
            this.bunifuTextBox6.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox6.PasswordChar = '\0';
            this.bunifuTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox6.PlaceholderText = "";
            this.bunifuTextBox6.ReadOnly = true;
            this.bunifuTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox6.SelectedText = "";
            this.bunifuTextBox6.SelectionLength = 0;
            this.bunifuTextBox6.SelectionStart = 0;
            this.bunifuTextBox6.ShortcutsEnabled = true;
            this.bunifuTextBox6.Size = new System.Drawing.Size(410, 52);
            this.bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox6.TabIndex = 33;
            this.bunifuTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox6.TextMarginBottom = 0;
            this.bunifuTextBox6.TextMarginLeft = 3;
            this.bunifuTextBox6.TextMarginTop = 0;
            this.bunifuTextBox6.TextPlaceholder = "";
            this.bunifuTextBox6.UseSystemPasswordChar = false;
            this.bunifuTextBox6.WordWrap = true;
            // 
            // penaltyPnlty
            // 
            this.penaltyPnlty.AcceptsReturn = false;
            this.penaltyPnlty.AcceptsTab = false;
            this.penaltyPnlty.AnimationSpeed = 200;
            this.penaltyPnlty.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.penaltyPnlty.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.penaltyPnlty.BackColor = System.Drawing.Color.Transparent;
            this.penaltyPnlty.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("penaltyPnlty.BackgroundImage")));
            this.penaltyPnlty.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyPnlty.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.penaltyPnlty.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            this.penaltyPnlty.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            this.penaltyPnlty.BorderRadius = 15;
            this.penaltyPnlty.BorderThickness = 2;
            this.penaltyPnlty.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.penaltyPnlty.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPnlty.DefaultFont = new System.Drawing.Font("Montserrat", 10F, System.Drawing.FontStyle.Bold);
            this.penaltyPnlty.DefaultText = "";
            this.penaltyPnlty.FillColor = System.Drawing.Color.White;
            this.penaltyPnlty.HideSelection = true;
            this.penaltyPnlty.IconLeft = null;
            this.penaltyPnlty.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPnlty.IconPadding = 10;
            this.penaltyPnlty.IconRight = null;
            this.penaltyPnlty.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.penaltyPnlty.Lines = new string[0];
            this.penaltyPnlty.Location = new System.Drawing.Point(477, 370);
            this.penaltyPnlty.MaxLength = 32767;
            this.penaltyPnlty.MinimumSize = new System.Drawing.Size(1, 1);
            this.penaltyPnlty.Modified = false;
            this.penaltyPnlty.Multiline = false;
            this.penaltyPnlty.Name = "penaltyPnlty";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPnlty.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.penaltyPnlty.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(245)))), ((int)(((byte)(198)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPnlty.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(96)))), ((int)(((byte)(108)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.penaltyPnlty.OnIdleState = stateProperties28;
            this.penaltyPnlty.Padding = new System.Windows.Forms.Padding(3);
            this.penaltyPnlty.PasswordChar = '\0';
            this.penaltyPnlty.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.penaltyPnlty.PlaceholderText = "";
            this.penaltyPnlty.ReadOnly = true;
            this.penaltyPnlty.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.penaltyPnlty.SelectedText = "";
            this.penaltyPnlty.SelectionLength = 0;
            this.penaltyPnlty.SelectionStart = 0;
            this.penaltyPnlty.ShortcutsEnabled = true;
            this.penaltyPnlty.Size = new System.Drawing.Size(201, 53);
            this.penaltyPnlty.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.penaltyPnlty.TabIndex = 34;
            this.penaltyPnlty.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.penaltyPnlty.TextMarginBottom = 0;
            this.penaltyPnlty.TextMarginLeft = 3;
            this.penaltyPnlty.TextMarginTop = 0;
            this.penaltyPnlty.TextPlaceholder = "";
            this.penaltyPnlty.UseSystemPasswordChar = false;
            this.penaltyPnlty.WordWrap = true;
            // 
            // returnPenalty
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.ClientSize = new System.Drawing.Size(1196, 554);
            this.Controls.Add(this.penaltyPnlty);
            this.Controls.Add(this.penaltyDReturned);
            this.Controls.Add(this.bunifuTextBox6);
            this.Controls.Add(this.penaltyDDate);
            this.Controls.Add(this.penaltyBTitle);
            this.Controls.Add(this.penaltyChange);
            this.Controls.Add(this.penaltyTotal);
            this.Controls.Add(this.penaltyPayment);
            this.Controls.Add(this.penaltyReturnBtn);
            this.Controls.Add(this.penaltyCalculateBtn);
            this.Controls.Add(this.lblPenaltyChange);
            this.Controls.Add(this.lblPenaltyPayment);
            this.Controls.Add(this.lblPenaltyTotal);
            this.Controls.Add(this.lblPenaltyPnlty);
            this.Controls.Add(this.lblPenaltyDReturned);
            this.Controls.Add(this.lblPenaltyDDate);
            this.Controls.Add(this.lblPenaltyBTitle);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "returnPenalty";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Bookify";
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel lblPenaltyHeader;
        private System.Windows.Forms.Label lblPenaltyBTitle;
        private System.Windows.Forms.Label lblPenaltyDDate;
        private System.Windows.Forms.Label lblPenaltyDReturned;
        private System.Windows.Forms.Label lblPenaltyPnlty;
        private System.Windows.Forms.Label lblPenaltyTotal;
        private System.Windows.Forms.Label lblPenaltyPayment;
        private System.Windows.Forms.Label lblPenaltyChange;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton penaltyCalculateBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton penaltyReturnBtn;
        private Bunifu.UI.WinForms.BunifuDatePicker penaltyDReturned;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyPayment;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyTotal;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyChange;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyBTitle;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyDDate;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox6;
        private Bunifu.UI.WinForms.BunifuTextBox penaltyPnlty;
    }
}